const radiostations = [
    {
        id: "197401",
        name: "Beach FM",
        stream: "https://sp0001.opengradle.pro:8040/live.mp3",
        stream_1: "",
        website: "",
        frequency: "105.5",
        location: "Takoradi",
        description: " Beach FM 105.5 is Takoradi's finest radio station. We cover Sekondi-Takoradi and the whole of Central Region of Ghana.",
        icon: "https://cdn-profiles.tunein.com/s277611/images/logoq.jpg?t=1",
        language: " Akan, English",
        genre: " Music, News, Sports, Talk",
        popular: false
    },
    {
        id: "197402",
        name: "Peace FM",
        stream: "https://peacefm-atunwadigital.streamguys1.com/peacefm?amsparams=playerid%3ASGplayer%3Bskey%3A1611468493100%3B&awparams=playerid%3ASGplayer%3Bplayerid%3ASGplayer%3Bplayerid%3ASGplayer%3B&us_privacy=1YNN&us_privacy=1YNN&us_privacy=1YNN",
        stream_1: "https://peacefm-atunwadigital.streamguys1.com/peacefm?amsparams=playerid%3ASGplayer%3Bskey%3A1609837847464%3B&awparams=playerid%3ASGplayer%3B&aw_0_req.gdpr=true&us_privacy=1YNN",
        website: "https://www.peacefmonline.com/",
        frequency: "104.3",
        location: "Accra",
        description: "Peace FM online is a radio station that is based in Acra, Ghana. It broadcasts a wide variety of contents such as local, national and international news, sports, business, current affairs, information and much more.",
        icon: "https://www.despitemedia.com/images/peacefmonline1.png",
        language: "Akan",
        genre: "Entertainment, News, Music, Politics, Sports, Variety",
        popular: true
    },
    {
        id: "197403",
        name: "Kente Radio",
        stream: "https://streamer.radio.co:80/s362651905/listen",
        stream_1: "",
        website: "https://www.kenteradio.com/",
        Frequency: "96.3",
        location: "Accra",
        description: "We serve Ghana's authentic and original music highlife music to the world.",
        icon: "https://cdn.onlineradiobox.com/img/logo/6/77106.v6.png",
        language: "Akan, English",
        genre: "Entertainment, Variety",
        popular: false
    },
    {
        id: "197404",
        name: "Skyy Power FM",
        stream: "https://node-13.zeno.fm/8ct99fxeq8quv?rj-ttl=5&rj-tok=AAABdteLwYoAcoGfvNmnU_W30w",
        stream_1: "",
        website: " http://skyypowerfm.com/",
        Frequency: "93.3",
        location: "Takoradi",
        description: "",
        icon: "https://skyypowerfm.com/wp-content/uploads/2020/04/skyy-power-fm-300x150.jpg",
        language: "Akan, English",
        genre: "Music, News, Sports, Talk",
        popular: true
    },
    {
        id: "197405",
        name: "Kesmi FM",
        stream: "https://node-10.zeno.fm/6zpesn9f4ceuv?rj-ttl=5&rj-tok=AAABdteJC44AXMBixYdah1pRCQ",
        stream_1: "",
        website: "http://www.kesmifmonline.com",
        Frequency: "107.1",
        location: "Tamale",
        description: "The Power Behind the Beat",
        icon: "https://cdn-profiles.tunein.com/s185596/images/logoq.jpg",
        language: "English",
        genre: "Music",
        popular: false
    },
    {
        id: "197407",
        name: "Ghana Waves Radio",
        stream: "https://node-10.zeno.fm/pg5c7zx3p0quv?rj-ttl=5&rj-tok=AAABdtd3XeAAU1f9o-yKlGaPXg",
        stream_1: "",
        website: "http://www.ghanawaves.com/",
        Frequency: "",
        location: "Unknown",
        description: "Ghana Waves Radio is the first Internet Radio Station in Ghana. It was set up for the benefit of Ghanaians Abroad. It broadcasts a great variety of contents, including news, information, lifestyle, sports, and much more.",
        icon: "https://ghanawaves.com//wp-content/uploads/2020/08/Ghana-Waves-Radio.png",
        language: "Akan, English",
        genre: "Music, News, Sports, Talk",
        popular: false
    },
    {
        id: "197408",
        name: "Rite Fm",
        stream: "http://ritefm.primcast.com:7554/;",
        stream_1: "",
        website: "https://ritefmonline.org/",
        Frequency: "90.1",
        location: "Somanya",
        description: "Owned and operated by FMSL Multimedia, Rite FM is a radio station located in Somanya, Volta. This radio was established to promote the agricultural and social development. Its most popular programme is Agricultural Forum.",
        icon: "https://cdn-radiotime-logos.tunein.com/s144817q.png",
        language: "English",
        genre: "Music, News, Sports, Talk",
        popular: false
    },
    {
        id: "197409",
        name: "Ark Fm",
        stream: "http://67.212.165.106:8247/;",
        stream_1: "",
        website: "https://www.arkfmonline.com/",
        Frequency: "107.1",
        location: "Sunyani",
        description: "Ark Fm is a private radio station based in Sunyani the regional capital. The station commenced commercial broadcasting in January 2007. The station employs English and Twi as its medium of communication and has a mix of adult and contemporary music, news and talk shows. The station boasts of a team of very young, dedicated and passionate staff whose inexplicable appetite for success has driven it to become one of the best in the sub region within its short period of existence.",
        icon: "https://cdn-profiles.tunein.com/s174197/images/logoq.png?t=156761",
        language: "Akan, English",
        genre: "Music, News, Talk",
        popular: false
    },
    {
        id: "197410",
        name: "Wett Fm",
        stream: "https://node-33.zeno.fm/uscwxqst9rquv?rj-ttl=5&rj-tok=AAABdtdOxZcAYMTIUevEBvmW8w",
        stream_1: "",
        website: "http://www.wettfm.com/",
        Frequency: "100.6",
        location: "Bogoso",
        description: "Urban Radio.",
        icon: "https://cdn-profiles.tunein.com/s301111/images/logoq.jpg?t=159726",
        language: "English",
        genre: "Music",
        popular: false
    },
    {
        id: "197411",
        name: "Trinity Fm",
        stream: "https://node-08.zeno.fm/ahu5c24tzwzuv?rj-ttl=5&rj-tok=AAABdtdJFHEAnT-sBtudr836tg",
        stream_1: "",
        website: "http://www.mytrinityfmonline.com/",
        Frequency: "96.7",
        location: "Bogoso",
        description: "Trinity 96.7fm is a radio station located at Bogoso in the Prestea Huni Valley District of the Western Region of Ghana.",
        icon: "https://cdn-radiotime-logos.tunein.com/s246053q.png",
        language: "Akan",
        genre: "Music",
        popular: false
    },
    {
        id: "197412",
        name: "Medeamaa Fm",
        stream: "https://node-06.zeno.fm/249ba9e1q0quv?rj-ttl=5&rj-tok=AAABdtdDxiMA0rjBvr_iSBVYvg",
        stream_1: "",
        website: "",
        Frequency: "92.9",
        location: "Bogoso",
        description: "Sports, Music politics and Current Affairs.",
        icon: "https://cdn-radiotime-logos.tunein.com/s245134q.png",
        language: "Akan",
        genre: "Music, Politics, Talk",
        popular: false
    },
    {
        id: "197413",
        name: "Fact Fm",
        stream: "https://stream.zeno.fm/xb7cwb5tzwzuv/;",
        stream_1: "",
        website: "http://factfmgh.com",
        Frequency: "104.3",
        location: "Bogoso",
        description: "Fact fm is a radio station located at Bogoso in the Prestea Huni Valley District of the Western Region of Ghana.",
        icon: "https://cdn-radiotime-logos.tunein.com/s269227q.png",
        language: "Akan",
        genre: "Variety",
        popular: false
    },
    {
        id: "197414",
        name: "Zuria Fm",
        stream: "https://atunwadigital.streamguys1.com/yfm1025kumasi",
        stream_1: "",
        website: "",
        Frequency: "88.7",
        location: "Kumasi",
        description: "Located in Kumasi, this is a very popular radio in the region. Zuria's programming focuses mostly on entertainment and music of various genres, but also includes talk shows, information and news.",
        icon: "https://cdn-radiotime-logos.tunein.com/s120870q.png",
        language: "Hausa",
        genre: "Music, News",
        popular: false
    },
    {
        id: "197415",
        name: "Yfm Fm",
        stream: "https://atunwadigital.streamguys1.com/yfm1025kumasi",
        stream_1: "",
        website: "https://www.yfmghana.com/",
        Frequency: "102.5",
        location: "Kumasi",
        description: "Based in Accra, Ghana, Y FM is a radio station that has been on air since 2008 targeting the younger listeners. Some of its most notable programmes are Mid Morning Show, Afropolitan Mix, Ryse & Shyne and Weekend Groove.",
        icon: "https://cdn-profiles.tunein.com/s187342/images/logoq.jpg?t=158644",
        language: "English",
        genre: "Music",
        popular: false
    },
    {
        id: "197416",
        name: "Uniiq Fm",
        stream: "https://node-34.zeno.fm/t13frkmd6bruv?rj-ttl=5&rj-tok=AAABdtaFNwkA1RElioLM9M8tAw",
        stream_1: "",
        website: "https://www.gbcghanaonline.com/",
        Frequency: "95.7",
        location: "Kumasi",
        description: "Uniiq - Uniiq FM formerly Radio GAR is the National Radio Station of the Ghana Broadcasting Corporation and airs on the Frequency 95.7FM.",
        icon: "https://cdn-profiles.tunein.com/s153509/images/logoq.jpg?t=156710",
        language: "English",
        genre: "News, Politics",
        popular: false
    },
    {
        id: "197417",
        name: "Ultimate Fm",
        stream: "https://node-09.zeno.fm/ac28vs4s6gwtv?rj-ttl=5&rj-tok=AAABdtZ_PecAOrIRs7xTreSUvQ",
        stream_1: "",
        website: "http://www.myradio360.com/",
        Frequency: "106.9",
        location: "Kumasi",
        description: "Totally different from the status quo!!! Easy adult listening, plenty of mid - tempo, R&B/Pop/ Soft Rock/Jazz/African (Authentic Ghanaian Highlife) music and less 'pointless' talk.",
        icon: "https://cdn-radiotime-logos.tunein.com/s161602q.png",
        language: "English",
        genre: "News",
        popular: false
    },
    {
        id: "197418",
        name: "Time Fm",
        stream: "http://freeus4.listen2myradio.com:36732/;",
        stream_1: "",
        website: "https://timefmghana.radiostream321.com/",
        Frequency: "96.9",
        location: "Kumasi",
        description: "TIME FM 96.9 Lifestyle Urban Contemporary Radio, driven by Music with an eclectic mix of relevant News/Talk and Sports........The Lifestyle Radio.",
        icon: "https://cdn-profiles.tunein.com/s234975/images/logoq.jpg?t=160521",
        language: "English",
        genre: "Entertainment, Music, News, Politics, Talk",
        popular: false
    },
    {
        id: "197419",
        name: "Sunsum Fm",
        stream: "https://shoutcast.k-planet.eu/9316/stream/1/",
        stream_1: "",
        website: "https://www.sunsumfm.com/",
        Frequency: "98.7",
        location: "Kumasi",
        description: "Broadcasting on 98.7 FM in in the local Akan language. This is a Christian gospel radio station in area of Kumasi, providing news, talk, music and entertainment....Enjoy the best of GOSPEL musics plus positive shows!",
        icon: "https://cdn-radiotime-logos.tunein.com/s224008q.png",
        language: "Akan",
        genre: "Gospel, News, Sports",
        popular: false
    },
    {
        id: "197420",
        name: "Shaft FM",
        stream: "http://argon.grottopress.com:8005/;",
        stream_1: "",
        website: "http://shaftfmonline.com",
        Frequency: "98.5",
        location: "Kumasi",
        description: "",
        icon: "https://cdn-radiotime-logos.tunein.com/s224929q.png",
        language: "Akan",
        genre: "Entertainment, News, Politics, Talk",
        popular: false
    },
    {
        id: "197421",
        name: "Sankofa Radio",
        stream: "https://ssl.nexuscast.com:8060/stream",
        stream_1: "",
        website: "https://www.sankofaradio.com/",
        Frequency: "98.5",
        location: "Kumasi",
        description: "Sankofa is an akan word that literally means 'Go back and fetch it.' It is an African wise saying that symbolizes learning from the past to build the future. A subsidiary of Sankofa Media Group, Sankofa Radio seeks to cater for the evolving needs of our listeners and the changing landscape of the media market. We will engage in stimulating and thought provoking conversations on issues affecting our community.",
        icon: "https://cdn-radiotime-logos.tunein.com/s111596q.png",
        language: "Akan",
        genre: "Music, News, Politics, Talk",
        popular: false
    },
    {
        id: "197422",
        name: "Pure FM",
        stream: "http://purefm.atunwadigital.streamguys1.com/purefm",
        stream_1: "",
        website: "http://mypurefmonline.com/",
        Frequency: "95.7",
        location: "Kumasi",
        description: "lifestyle radio",
        icon: "https://cdn-profiles.tunein.com/s293349/images/logoq.png?t=155861",
        language: "English",
        genre: "Music, News",
        popular: false
    },
    {
        id: "197423",
        name: "Otec FM",
        stream: "https://node-21.zeno.fm/2dnt5ku7fxquv?rj-ttl=5&rj-tok=AAABdtZlO9EA0tIq-U0mKCZ9cg",
        stream_1: "",
        website: "http://otecfmghana.com/",
        Frequency: "102.9",
        location: "Kumasi",
        description: "A private radio station in the Ashanti region, Ghana, Africa and beyond. Broadcasting on 102.9 FM with a great african and english music you will hear everyda, even you are at home or at the office.",
        icon: "https://cdn-radiotime-logos.tunein.com/s238886q.png",
        language: "Akan, English",
        genre: "Entertainment, Music, News, Talk",
        popular: false
    },
    {
        id: "197424",
        name: "Light FM GH",
        stream: "http://41.215.162.91:9490/stream",
        stream_1: "",
        website: "http://lightfmghana.com/",
        Frequency: "94.9",
        location: "Kumasi",
        description: "",
        icon: "https://cdn-profiles.tunein.com/s276804/images/logoq.png?t=152759",
        language: "Akan, English",
        genre: "Music, News",
        popular: false
    },
    {
        id: "197425",
        name: "Kessben FM",
        stream: "https://node-27.zeno.fm/z8fx1065puquv?rj-ttl=5&rj-tok=AAABdtZZRq8Ak0dOaaf1lhN_RA",
        stream_1: "",
        website: "https://kessbenfm.com/",
        Frequency: "93.3",
        location: "Kumasi",
        description: "Kessben FM is a radio station that broadcasts from Aseda House to most of the regions of the country. Its programming includes several contents such as information and entertainment.",
        icon: "https://cdn.webrad.io/images/logos/radio-com-gh/kessben-fm.png",
        language: "Akan, English, Multilingual",
        genre: "Top 40, Music, Variety",
        popular: true
    },
    {
        id: "197426",
        name: "Gye Nyame FM",
        stream: "https://node-01.zeno.fm/qr1ruc527mwtv?rj-ttl=4&rj-tok=AAABdtZVH2UANLKomvdj_4GDuA",
        stream_1: "",
        website: "https://www.gyenyamefm.com/",
        Frequency: "94.5",
        location: "Kumasi",
        description: "",
        icon: "https://cdn-radiotime-logos.tunein.com/s155997q.png",
        language: "Akan, English, Multilingual",
        genre: "Gospel, Music, Variety",
        popular: false
    },
    {
        id: "197427",
        name: "Fox FM",
        stream: "https://node-29.zeno.fm/w5h08t2e48vtv?rj-ttl=5&rj-tok=AAABdtZN08wAD2ZJ-xhCdD7aZg",
        stream_1: "",
        website: "https://news.foxfmonline.com/",
        Frequency: "97.9",
        location: "Kumasi",
        description: "This is a multilingual radio station that broadcasts from Garden City, Oseikrom, Ghana, and can be listened both on 97.9 FM and online. Fox Fm plays the best music 24 hours a day, 7 days a week.",
        icon: "https://cdn-radiotime-logos.tunein.com/s142087q.png",
        language: "Akan, English, Multilingual",
        genre: "Gospel, Music, Variety",
        popular: false
    },
    {
        id: "197428",
        name: "Focus FM",
        stream: "https://node-29.zeno.fm/w5h08t2e48vtv?rj-ttl=5&rj-tok=AAABdtZN08wAD2ZJ-xhCdD7aZg",
        stream_1: "",
        website: "https://focusnewsroom.com/",
        Frequency: "94.3",
        location: "Kumasi",
        description: "Drive Time",
        icon: "https://cdn-profiles.tunein.com/s200023/images/logoq.jpg?t=157139",
        language: "Akan, English, Multilingual",
        genre: "Gospel, Music, Variety",
        popular: false
    },
    {
        id: "197429",
        name: "Ezra FM",
        stream: "https://node-18.zeno.fm/ps7uuqzhp2zuv.aac?rj-ttl=5&rj-tok=AAABdtZIFcgAkM8kWj6xVdIkhA",
        stream_1: "",
        website: "https://metrofm.online/",
        Frequency: "94.1",
        location: "Kumasi",
        description: "Ezra FM is a radio station that broadcasts from Kumasi, Ghana. It features a mix of various contents such as entertainment, news and sports. Its team of professionals includes Ray Charles Marfo, William, Thomas Freeman, Kwakye and many Unknown.",
        icon: "https://cdn-profiles.tunein.com/s183233/images/logoq.png?t=160631",
        language: "Akan, English, Multilingual",
        genre: "News, Politics, Talk, Sport News",
        popular: false
    },
    {
        id: "197430",
        name: "Boss FM",
        stream: "http://178.32.62.154:9600/;",
        stream_1: "",
        website: "http://www.bossfmghana.com/",
        Frequency: "93.7",
        location: "Kumasi",
        description: "Boss 93.7 FM is a private radio station that commenced on the first day of June 2008. The station has an array of competent professionals who aspire to make a name not only for themselves but the broadcast industry as a whole.",
        icon: "https://cdn-radiotime-logos.tunein.com/s140478q.png",
        language: "Multilingual",
        genre: "Variety",
        popular: false
    },
    {
        id: "197406",
        name: "Bohye FM",
        stream: "https://node-04.zeno.fm/971yzruu5yzuv?rj-ttl=5&rj-tok=AAABdtY96MAA0XfTz7esTBkXDQ",
        stream_1: "",
        website: "http://bohyeonline.com/",
        Frequency: "95.3",
        location: "Kumasi",
        description: "Bohye FM 95.3 is also noted for relevant events like the Sports, Preachings and Bohye Drive etc. Advertising on Bohye FM 95.3 The news team is backed by a vibrant sales and client service team that creates tailored products for advertisers and clients. Bohye FM 95.3’s key strength lies in our ability to design tailored advertising and promotional packages for businesses in a fast and cost effective manner. Your products, events and services will get to an ever growing audience of engaging listeners and patrons who believe in the credibility of what we communicate.",
        icon: "https://cdn-radiotime-logos.tunein.com/s229860q.png",
        language: "Akan, English, Multilingual",
        genre: "Entertainment, Gospel, News, Talk",
        popular: false
    },
    {
        id: "197431",
        name: "Asenteman Radio",
        stream: "https://node-31.zeno.fm/whaba8v8d4duv?rj-ttl=5&rj-tok=AAABdtY3N84AAc3outs3-ohyeA",
        stream_1: "",
        website: "https://www.asantemanradioonline.com/",
        Frequency: "",
        location: "Kumasi",
        description: "",
        icon: "https://cdn-profiles.tunein.com/s224923/images/bannerx.jpg?t=636808145780000000",
        language: "Akan, English, Multilingual",
        genre: "Music",
        popular: false
    },
    {
        id: "197432",
        name: "Angel FM",
        stream: "https://atunwadigital.streamguys1.com/angelfm",
        stream_1: "",
        website: "https://angelfmonlinegh.com/",
        Frequency: "96.1",
        location: "Kumasi",
        description: "On air since 2007, Angel FM is located in Kumasi and serves the region of Ashanti and its surroundings. This is a very popular radio that features music, entertainment, information and news.",
        icon: "https://cdn-profiles.tunein.com/s110138/images/logoq.jpg?t=158204",
        language: "Akan, Multilingual",
        genre: "Arts, Entertainment, Music, News",
        popular: true
    },
    {
        id: "197433",
        name: "66 WNBC",
        stream: "https://prod-104-198-105-188.wostreaming.net/marshfield-wmexamaac-ibc1?",
        stream_1: "",
        website: "http://www.66wnbc.com/",
        Frequency: "96.1",
        location: "Kumasi",
        description: "Flagship radio station of the National Broadcasting Company.",
        icon: "https://cdn-profiles.tunein.com/s140136/images/logog.png?t=157737",
        language: "Multilingual",
        genre: "News, Sports, Talk",
        popular: false
    },
    {
        id: "197434",
        name: "Alpha Radio",
        stream: "http://89.163.217.252:9336/;",
        stream_1: "",
        website: "http://alpharadioonline.com",
        Frequency: "104.9",
        location: "Kumasi",
        description: "Flagship radio station of the National Broadcasting Company.",
        icon: "https://cdn-radiotime-logos.tunein.com/s254654q.png",
        language: "Multilingual",
        genre: "Music",
        popular: false
    },
    {
        id: "197435",
        name: "Apo Radio",
        stream: "https://node-13.zeno.fm/u3hsadvwcg0uv?rj-ttl=5&rj-tok=AAABdtOWnjQAJyTtTtbGQG4jnQ",
        stream_1: "",
        website: "http://www.apomediaplus.com/",
        Frequency: "101.1",
        location: "Kumasi",
        description: "Serving You With Media Broadcasting.",
        icon: "https://cdn-profiles.tunein.com/s265593/images/logoq.jpg?t=160693",
        language: "Multilingual",
        genre: "Music",
        popular: false
    },
    {
        id: "197436",
        name: "Ashh Fm",
        stream: "https://atunwadigital.streamguys1.com/ashhfm",
        stream_1: "",
        website: "https://myashhfmonline.com/",
        Frequency: "101.1",
        location: "Kumasi",
        description: "Ashh FM is a radio station that broadcasts from Kumasi. It is available both on 101.1 FM and online. This radio station is on air 24 hours a day, 7 days a week, featuring music of various genres.",
        icon: "https://cdn-profiles.tunein.com/s120874/images/logog.jpg?t=154418",
        language: "Akan, Multilingual",
        genre: "Music",
        popular: false
    },
    {
        id: "197437",
        name: "Ghana Today Radio",
        stream: "http://stream2.ghanatoday.com/gtonline",
        stream_1: "",
        website: "http://www.ghanatoday.com/",
        Frequency: "",
        location: "Accra",
        description: "Ghana Today, The Information Gateway to Ghana offering the latest Ghana based news, sport, tourism, entertainments, music, dating and much more.",
        icon: "https://cdn-radiotime-logos.tunein.com/s105674q.png",
        language: "English, Multilingual",
        genre: "News",
        popular: false
    },
    {
        id: "197438",
        name: "Happy Fm",
        stream: "https://atunwadigital.streamguys1.com/happyfm989accra",
        stream_1: "",
        website: "https://www.happyghana.com/",
        Frequency: "98.9",
        location: "Accra",
        description: "Happy FM was launched in 2002 aiming to serve the population with sports contents. In 2010, other type of programmes were added to its schedule. It broadcasts to Accra and the surrounding regions.",
        icon: "https://cdn.webrad.io/images/logos/radio-com-gh/happy-fm.png",
        language: "Akan, English",
        genre: "News",
        popular: true
    },
    {
        id: "197439",
        name: "High Life Radio",
        stream: "http://188.165.240.90:8676/stream",
        stream_1: "",
        website: "http://hiliferadio.com/",
        Frequency: "",
        location: "USA",
        description: "Highlife Radio is a US based Ghanaian community online radio station dedicated to providing diverse, stimulating and high quality programming to the Ghanaian Diaspora. HighLife Radio was created as a medium to bring about a sense of community.",
        icon: "https://cdn-radiotime-logos.tunein.com/s144129q.png",
        language: "Akan, English",
        genre: "Entertainment, Music, News, Talk",
        popular: false
    },
    {
        id: "197440",
        name: "Kasapa Fm",
        stream: "https://node-14.zeno.fm/3eh6htuyk8quv?rj-ttl=5&rj-tok=AAABdtNl8EgAdZnDMY_58aoknA",
        stream_1: "",
        website: "http://www.kasapafmonline.com",
        Frequency: "102.5",
        location: "Accra",
        description: "KASAPA FM is an urban, lifestyle radio station, which focuses on the delivery of compelling programmes through good music, entertainment/lifestyle- led talk programmes and sports for its target audience. In respect of News and Current affairs, we seek to deliver accurate, factual, relevant and newsworthy stories to our listeners. Entertainment and Lifestyle stories will be a strong feature of our news. We seek to entertain and educate our target listeners through music and talk content that we put out there on air, through our events and promotions.",
        icon: "https://cdn-radiotime-logos.tunein.com/s174903g.png",
        language: "Akan, English",
        genre: "Entertainment, Music, News, Talk",
        popular: false
    },
    {
        id: "197441",
        name: "Koowaa Fm",
        stream: "http://the.radioservers.biz:9852/;",
        stream_1: "",
        website: "http://koowaa.com/",
        Frequency: "",
        location: "Accra",
        description: "We are Pan-African radio station and we broadcast live from our studios in UK and Ghana. We give voice to the voiceless, we education, entertain and engage our community.",
        icon: "https://cdn-profiles.tunein.com/s252600/images/logoq.jpg?t=636293",
        language: "Akan, English, Multilingual",
        genre: "Entertainment, Music, News, Talk",
        popular: false
    },
    {
        id: "197442",
        name: "LiveXtra Fm",
        stream: "https://node-29.zeno.fm/7586sp6mua0uv?rj-ttl=5&rj-tok=AAABdtK_vI8AwopbZYmWFHLrNw",
        stream_1: "",
        website: "http://livefmghana.com/",
        Frequency: "91.9",
        location: "Accra",
        description: "LIVE 91.9FM Lifestyle Urban Contemporary Radio, driven by Music with an eclectic mix of relevant News/Talk and Sports........The Lifestyle Radio.",
        icon: "http://livextragh.com/wp-content/uploads/2020/09/livextra_logo.jpeg",
        language: "English",
        genre: "Music",
        popular: false
    },
    {
        id: "197443",
        name: "Nkonim Fm",
        stream: "https://stream.lensnetworks.com/proxy/nkonim?mp=/stream",
        stream_1: "",
        website: "http://www.nkonimfm.com/",
        Frequency: "93.7",
        location: "Accra",
        description: "Our focus is to uplift, educate and bring our culture and family values to the world through our traditional music.",
        icon: "https://cdn-radiotime-logos.tunein.com/s268131g.png",
        language: "Multilingual",
        genre: "Music",
        popular: false
    },
    {
        id: "197444",
        name: "Oman Fm",
        stream: "https://omanfm-atunwadigital.streamguys1.com/omanfm?amsparams=playerid%3ASGplayer%3Bskey%3A1611555812774%3B&awparams=playerid%3ASGplayer%3Bplayerid%3ASGplayer%3Bplayerid%3ASGplayer%3B&aw_0_req.gdpr=true&us_privacy=1YNN&aw_0_req.gdpr=true&us_privacy=1YNN&aw_0_req.gdpr=true&us_privacy=1YNN",
        stream_1: "http://omanfm.atunwadigital.streamguys1.com/omanfm",
        website: "https://www.omanfm1071.com/",
        Frequency: "107.1",
        location: "Accra",
        description: "Oman fm is a subsidiary of KENCITY MEDIA LIMITED, operators of NET 2 TV, the NATIONAL AGENDA newspaper, ASHH FM in Kumasi and SPICE FM in Takoradi. The station operates from the HOLLYWOOD building in Madina,a suburb of Accra.OMANFM SHAPING THE NATION.",
        icon: "https://www.omanfm1071.com/wp-content/uploads/2019/04/oman_logo-.jpg",
        language: "Akan, English, Multilingual",
        genre: "Variety",
        popular: true
    },
    {
        id: "197445",
        name: "Onua Fm",
        stream: "https://node-08.zeno.fm/hmz5ma42u8quv?rj-ttl=5&rj-tok=AAABdtKgHpwAzwol2DkUn-Po-A",
        stream_1: "",
        website: "http://3news.com/onuafm/",
        Frequency: "95.1",
        location: "Accra",
        description: "Onua95.1 FM is an Akan (local dialect ) speaking Station which co-locate with it sister stations, 3FM and TV3 Network in the city of Ghana.It target listeners are the small scale business, the market women, and the Mass market as a whole.",
        icon: "https://pbs.twimg.com/profile_images/1328344353438306305/iETcw9mq_400x400.jpg",
        language: "Akan",
        genre: "Variety",
        popular: false
    },
    {
        id: "197446",
        name: "XYZ Fm",
        stream: "https://node-32.zeno.fm/21wv4hn4f3quv?rj-ttl=5&rj-tok=AAABdtKTG5AAAuriWKBE1HV2wQ",
        stream_1: "",
        website: "http://myxyzonline.com/",
        Frequency: "93.1",
        location: "Accra",
        description: "Broadcasting from Osu, Accra, Ghana, Radio XYZ is a radio station that focuses its programming on several contents such as local and national news, sports, entertainment, business, international information and much more.",
        icon: "https://cdn-profiles.tunein.com/s155684/images/logoq.jpg?t=156586",
        language: "Akan, English",
        genre: "News, Variety",
        popular: false
    },
    {
        id: "197447",
        name: "Rainbow Radio",
        stream: "https://node-15.zeno.fm/wv4tseqxk8quv?rj-ttl=5&rj-tok=AAABdtKQ-zAApp8i1nvprbjDlw",
        stream_1: "",
        website: "https://rainbowradioonline.com/",
        Frequency: "87.5",
        location: "Accra",
        description: "The best of afrobeat, hiplife, hi-life and great talk.",
        icon: "https://imgproxy.zenomedia.com/insecure/fit/380/380/ce/0/plain/https://proxy.zeno.fm/content/stations/agxzfnplbm8tc3RhdHNyMgsSCkF1dGhDbGllbnQYgICA4LLwzggMCxIOU3RhdGlvblByb2ZpbGUYgICAgPLskQoMogEEemVubw/image/%3Fresize=380x380&v=1",
        language: "English",
        genre: "Music, Talk",
        popular: false
    },
    {
        id: "197448",
        name: "Spirit FM",
        stream: "https://node-32.zeno.fm/sde1ug58vqzuv?rj-ttl=5&rj-tok=AAABdtKJ1n4Adec9n2wbW2QHDg",
        stream_1: "",
        website: "http://www.spiritfmonline.com/",
        Frequency: "90.7",
        location: "Accra",
        description: "Spirit FM is a radio station that broadcasts a wide variety of contents, including news, sports, politics, business, entertainment, lifestyle, education and much more.",
        icon: "https://cdn-profiles.tunein.com/s252704/images/logoq.jpg?t=158160",
        language: "Akan, English",
        genre: "Entertainment, News, Politics, Sports",
        popular: false
    },
    {
        id: "197449",
        name: "Starr FM",
        stream: "https://node-22.zeno.fm/2sukc50nqxquv?rj-ttl=5&rj-tok=AAABdtKGA_wAjmHjl9ie0L__1g",
        stream_1: "",
        website: "http://www.starrfmonline.com/",
        Frequency: "103.5",
        location: "Accra",
        description: "STARR 103.5 FM is an urban, lifestyle radio station, which focuses on the delivery of compelling programmes through good music, entertainment/lifestyle- led talk programmes and sports for its target audience. In respect of News and Current affairs, we seek to deliver accurate, factual, relevant and newsworthy stories to our listeners. Entertainment and Lifestyle stories will be a strong feature of our news. We seek to entertain and educate our target listeners through music and talk content that we put out there on air, through our events and promotions.",
        icon: "https://cdn-radiotime-logos.tunein.com/s229680g.png",
        language: "English",
        genre: "News, Politics, Talk",
        popular: false
    },
    {
        id: "197450",
        name: "Sweet Melodies FM",
        stream: "http://197.251.194.215:8000/stream",
        stream_1: "",
        website: "https://www.sweetmelodiesfm.com/",
        Frequency: "94.3",
        location: "Accra",
        description: "Sweet Melodies is a Christian radio station that broadcasts from Accra since it was established in 2009. Its programming includes contemporary Christian music, news, preaching, Bible teachings and much more.",
        icon: "https://cdn-profiles.tunein.com/s165738/images/logog.jpg?t=159001",
        language: "English, Multilingual",
        genre: "Gospel, Music, News, Variety",
        popular: false
    },
    {
        id: "197451",
        name: "Top FM",
        stream: "https://node-31.zeno.fm/41s7mm90mtwtv.aac?rj-ttl=5&rj-tok=AAABdtPzU2oAi9ujklDNuB0GUg",
        stream_1: "",
        website: "https://topfmonline.com/",
        Frequency: "103.1",
        location: "Accra",
        description: "Broadcasting from accra, Top 103.1 FM is a radio station that features a wide variety of contents, such as entertainment and music, news and information, politics, economics, sports and much more.",
        icon: "https://cdn-radiotime-logos.tunein.com/s134525g.png",
        language: "Akan, English",
        genre: "Entertainment, News, Politics, Sports, Variety",
        popular: true
    },
    {
        id: "197452",
        name: "XLive Africa",
        stream: "http://178.32.62.163:8785/",
        stream_1: "",
        website: "http://xliveafrica.com/",
        Frequency: "95.1",
        location: "Accra",
        description: "Located in Osu, Accra, X Live Africa is a radio station that started broadcasting in 2009. This is an entertainment radio that features some of the following programmes: Crazi X Show, Crazi X Show, Nite Xpress, Press Play and X-Heal.",
        icon: "https://cdn-radiotime-logos.tunein.com/s129383g.png",
        language: "Akan, English",
        genre: "Top 40, Music, Variety",
        popular: false
    },
    {
        id: "197453",
        name: "YFm 979 Takoradi",
        stream: "https://atunwadigital.streamguys1.com/yfm979takoradi",
        stream_1: "",
        website: "https://yfmghana.com/",
        Frequency: "97.9",
        location: "Takoradi",
        description: "This radio is made by and for youth in age or in spirit. Its programming has a diversity of shows, music, entertainment, and information. It is on air every day, from Ghana.",
        icon: "https://cdn-profiles.tunein.com/s208875/images/logog.jpg?t=157140",
        language: "Akan, English",
        genre: "Entertainment, News, Music, Variety",
        popular: false
    },
    {
        id: "197454",
        name: "YFm Accra",
        stream: "https://atunwadigital.streamguys1.com/yfm1079accra",
        stream_1: "",
        website: "https://www.yfmghana.com/",
        Frequency: "107.9",
        location: "Accra",
        description: "YFM Ghana is a radio station with a programming focused on entertainment and music. It features shows such as Afropolitan Mix, Dryve of your Life, Y Lounge and Weekend Groove.",
        icon: "https://cdn-profiles.tunein.com/s208875/images/logog.jpg?t=157140",
        language: "Akan, English",
        genre: "Entertainment, News, Music, Variety",
        popular: true
    },
    {
        id: "197455",
        name: "Akasanoma Radio Ghana",
        stream: "https://node-03.zeno.fm/ey0fyngxva5tv?rj-ttl=5&rj-tok=AAABdtJm504AW5lq2VEfNA4C6g",
        stream_1: "",
        website: "http://ghananet.weebly.com/",
        Frequency: "92.3",
        location: "Unknown",
        description: "",
        icon: "https://cdn-radiotime-logos.tunein.com/s16142g.png",
        language: "Akan",
        genre: "Music",
        popular: false
    },
    {
        id: "197456",
        name: "Ahotor Fm",
        stream: "https://node-07.zeno.fm/bbpfy9pk21zuv?rj-ttl=5&rj-tok=AAABdtJi4QkAQOQEu89yxCY6mw",
        stream_1: "",
        website: "http://www.ahotoronline.com/",
        Frequency: "92.3",
        location: "Unknown",
        description: "You are Welcome to Ahotor 92.3 FM. We are here to give You Quality News, Social and Political Talk-shows, Sports, Inspirational and Entertainment Programs. Ahotor 92.3 FM, is a brand new Radio Station Transmitting live from Tema, Accra - Ghana. We are here to give you only the best. Ahotor FM, we are your Voice of Inspiration, Information, Education and Entertainment For Great Music, Quality Sound and Inspirational Radio Broadcasting Tune-in to Ahotor 92.3 FM. Transmitting live from Accra - Ghana. Our DJs are the best and you will love their choice of music selections. Our Presenters are great with life-style everyday situational and social and Political Programs from Ghana, and the World.",
        icon: "https://cdn-radiotime-logos.tunein.com/s270288g.png",
        language: "Akan",
        genre: "Music, News, Politics, Sports,Talk",
        popular: false
    },
    {
        id: "197457",
        name: "3Fm",
        stream: "https://node-20.zeno.fm/hk573nh6sm0uv?rj-ttl=5&rj-tok=AAABdtJbmtMAYMO1OM34wOfUoA",
        stream_1: "",
        website: "https://3news.com/",
        Frequency: "92.7",
        location: "Unknown",
        description: "This is an English speaking station which is located in the Capital city of Ghana. It target listeners are discerning people. 3FM is a sister station to Onua FM, an Akan speaking station and Tv3, all located on the same compound.",
        icon: "https://cdn-profiles.tunein.com/s273129/images/logog.jpg?t=151915",
        language: "English, Multilingual",
        genre: "Music, Variety",
        popular: true
    },
    {
        id: "197458",
        name: "Nhyira Fm",
        stream: "https://mmg.streamguys1.com/NhyiraFM-mp3?key=b37c365ed033b3e65a85fc860f6611ee8562838eeb6e0489764968a4153d826217219cfacc395f2cc2389573fb59870a&awparams=playerid%3ASGplayer%3B&amsparams=playerid%3ASGplayer%3Bskey%3A1609844395217%3B&aw_0_req.gdpr=true&us_privacy=1YNN",
        stream_1: "",
        website: "https://www.myjoyonline.com/",
        Frequency: "104.5",
        location: "Kumasi",
        description: "Nhyria FM is a radio station that broadcasts from Kumasi since 2011. Its contents are very similar to the contents its sister radios broadcast: news, sport, politics, world news, business and entertainment.",
        icon: "https://player.streamguys.com/atunwa/mgl/nhyirafm/include/image/nhyirafm-logo.png",
        language: "Akan, Multilingual",
        genre: "Entertainment, News, Politics, Sports, Variety",
        popular: true
    },
    {
        id: "197459",
        name: "Luv Fm",
        stream: "https://mmg.streamguys1.com/LuvFM-mp3?key=64c68f3397eadf448520da5c47847f30b48defff1ca52821a9d5817e516774af24fe51fe4829d41ccf1b4b9d0eca1eec&awparams=playerid%3ASGplayer%3B&amsparams=playerid%3ASGplayer%3Bskey%3A1609844133655%3B&aw_0_req.gdpr=true&us_privacy=1YNN",
        stream_1: "",
        website: "https://www.myjoyonline.com/",
        Frequency: "99.5",
        location: "Kumasi",
        description: "Owned and operated by Multimedia Group Limited, Luv FM is a radio station located in Kumasi, in the Ashanti region. It broadcasts local news, information, talk shows and music in English.",
        icon: "https://player.streamguys.com/atunwa/mgl/luvfm/include/image/luvfm-logo.png",
        language: "Akan, English, Multilingual",
        genre: "Entertainment, News, Politics",
        popular: true
    },
    {
        id: "197460",
        name: "Asempa Fm",
        stream: "https://mmg.streamguys1.com/AsempaFM-mp3?key=23f81ad063fc94d769b3f56668d742562a0645bb7ba0f5633dbce7d73d151195adfd4a7b4b2afeeff7fb81cf4ef6e790&awparams=playerid%3ASGplayer%3B&amsparams=playerid%3ASGplayer%3Bskey%3A1609843961148%3B&aw_0_req.gdpr=true&us_privacy=1YNN",
        stream_1: "",
        website: "https://www.myjoyonline.com/",
        Frequency: "94.7",
        location: "Accra",
        description: "Asempa FM is a radio station that is located in Ghana. It was launched in 2007 to make the difference in the market. Its programming is dedicated to talk shows with focus on current affairs and sports.",
        icon: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvvDQVvTFoGoa6mS_YzCiR6X_1wKA7SaTEuQ&usqp=CAU",
        language: "Akan",
        genre: "Entertainment, News, Politics, Sports, Variety",
        popular: true
    },
    {
        id: "197461",
        name: "Hitz Fm",
        stream: "https://mmg.streamguys1.com/HitzFM-mp3?key=5fe042be16f6c99a028891bea3969b6ec4ee63a89cb0b8f90ac26e376ad11de1c232b8dd38f8df13232d6398bd56da8c&awparams=playerid%3ASGplayer%3B&amsparams=playerid%3ASGplayer%3Bskey%3A1609843252244%3B&aw_0_req.gdpr=true&us_privacy=1YNN",
        stream_1: "",
        website: "https://www.myjoyonline.com/",
        Frequency: "94.7",
        location: "Accra",
        description: "Hitz FM is an entertainment radio station located in Accra, Ghana. It is owned and operated by Multimedia Group Limited, a media group launched in 1995. Some of its most popular programmes are Hitz Gospel, Hitz Gallery, Hitz in De Klub and Hilife Bosue.",
        icon: "https://www.myjoyonline.com/wp-content/uploads/news/201207/265639382_567583.jpg",
        language: "Akan",
        genre: "Entertainment, News, Politics, Sports, Variety",
        popular: true
    },
    {
        id: "197462",
        name: "Adom Fm",
        stream: "https://mmg.streamguys1.com/AdomFM-mp3?key=9099965b0e49394af3be11b42a71f0faa90378311d2d85f5983495217e350f0a4636df5ecf5ea3f63e53cb9026d89102&awparams=playerid%3ASGplayer%3B&amsparams=playerid%3ASGplayer%3Bskey%3A1609841442537%3B&aw_0_req.gdpr=true&us_privacy=1YNN",
        stream_1: "",
        website: "https://www.adomonline.com/",
        Frequency: "106.3 ",
        location: "Tema",
        description: "Located in Tema, Ghana, Adom FM is a radio station that broadcasts a wide variety of contents, including news, sports, politics, business, entertainment, lifestyle, education and much more.",
        icon: "https://cdn.webrad.io/images/logos/radio-com-gh/adom-fm.png",
        language: "Akan",
        genre: "Entertainment, News, Politics, Sports, Variety",
        popular: true
    },
    {
        id: "197463",
        name: "Joy Fm",
        stream: "https://mmg.streamguys1.com/JoyFM-mp3?key=8689cc761932e3151f94ddbdbfdf4aa0f4000234b5caeaaa179a2fc0d59a4be9b8b774c3653cb14d1fd76f5cbf80e482&awparams=playerid%3ASGplayer%3B&amsparams=playerid%3ASGplayer%3Bskey%3A1609840716923%3B&aw_0_req.gdpr=true&us_privacy=1YNN",
        stream_1: "",
        website: "https://www.myjoyonline.com/",
        Frequency: "99.7",
        location: "Accra",
        description: "This is a radio station that broadcasts from Accra, Ghana. One of the most popular radio platforms in Ghana, it features a wide variety of programmes that include news, entertainment, information and sports.",
        icon: "https://cdn-profiles.tunein.com/s7540/images/logog.png?t=152102",
        language: "English",
        genre: "Entertainment, News, Politics, Sports, Variety",
        popular: true
    },
    {
        id: "197464",
        name: "Citi Fm",
        stream: "https://node-02.zeno.fm/g6zrd965puquv?rj-ttl=5&rj-tok=AAABdzMGxHkA0gChlANYeag7xg",
        stream_1: "https://citi973fm.radioca.st/stream/1/",
        website: "https://citifmonline.com/",
        Frequency: "97.3",
        location: "Accra",
        description: "On air since 2004, Citi FM is a private radio station located in Accra. It features a mix of news, talk shows and adult contemporary music. Some of its most notable programmes are Brunch In The Citi, Citi Drive and Citi FM Break Fast Show.",
        icon: "https://cdn-profiles.tunein.com/s110136/images/logog.png?t=157001",
        language: "English",
        genre: "Entertainment, News, Politics, Sports, Variety",
        popular: true
    },
    {
        id: "197465",
        name: "Neat Fm",
        stream: "https://atunwadigital.streamguys1.com/neatfm",
        stream_1: "https://neatfm-atunwadigital.streamguys1.com/neatfm?amsparams=playerid%3ASGplayer%3Bskey%3A1609838307482%3B&awparams=playerid%3ASGplayer%3B&aw_0_req.gdpr=true&us_privacy=1YNN",
        website: "https://neatfm.peacefmonline.com/",
        Frequency: "97.3",
        location: "Accra",
        description: "Neat FM is your news, politics and entertainment radio station in Accra, providing you with latest peculiar but true religious news content.",
        icon: "https://www.mytunein.com/images/logos/neat1009fm.jpg",
        language: "Akan",
        genre: "Entertainment, News, Music, Politics, Sports, Variety",
        popular: true
    },
    {
        id: "197466",
        name: "Hello Fm",
        stream: "https://atunwadigital.streamguys1.com/hellofm",
        stream_1: "https://hellofm-atunwadigital.streamguys1.com/hellofm?amsparams=playerid%3ASGplayer%3Bskey%3A1609838237601%3B&awparams=playerid%3ASGplayer%3B&aw_0_req.gdpr=true&us_privacy=1YNN",
        website: "https://hellofm.peacefmonline.com/",
        Frequency: "101.3",
        location: "Kumasi",
        description: "Hello FM is part of Peace FM online and broadcasts from Accra. It features a mix of local, national and international news and information, business, sports, politics, showbiz and much more.",
        icon: "https://www.despitemedia.com/images/hello.jpg",
        language: "Akan",
        genre: "Entertainment, News, Music, Politics, Sports, Variety",
        popular: false
    },
    {
        id: "197467",
        name: "Okay Fm",
        stream: "http://okayfm.atunwadigital.streamguys1.com/okayfm",
        stream_1: "https://okayfm-atunwadigital.streamguys1.com/okayfm?amsparams=playerid%3ASGplayer%3Bskey%3A1609838142774%3B&awparams=playerid%3ASGplayer%3B&aw_0_req.gdpr=true&us_privacy=1YNN",
        website: "https://okayfm.peacefmonline.com/",
        Frequency: "101.7",
        location: "Accra",
        description: "Broadcasting from Accra, Ghana, Okay FM is a radio station that is available both on 101.7 FM and online. Its programming focuses mostly on national and international news and information. Hello FM is part of Peace FM online and broadcasts from Accra.",
        icon: "https://media-exp1.licdn.com/dms/image/C4E0BAQG5cPPTKAw0rg/company-logo_200_200/0/1565285120140?e=2159024400&v=beta&t=3f5W-lhKfL1vLGXD6LCzsKbK_TdxvX9h9oN4PD0jPkM",
        language: "Akan",
        genre: "Entertainment, News, Music, Variety",
        popular: true
    },
    {
        id: "197468",
        name: "Twin City Radio",
        stream: "http://stream1.iradeo.com:9034/iradeo",
        stream_1: "",
        website: "https://www.twincityradio.com/",
        Frequency: "94.7",
        location: "Takoradi",
        description: "Twin City Radio(Ghana Broadcasting Corporation) (TCR) (GBC) is bringing you news, analysis.",
        icon: "https://cdn.onlineradiobox.com/img/logo/8/73058.v5.png",
        language: "Akan",
        genre: "News, Talk, Sports",
        popular: true
    },
    {
        id: "197469",
        name: "Spice Fm",
        stream: "https://sp0001.opengradle.pro:8030/live.mp3?ver=8616",
        stream_1: "",
        website: "http://www.spicefmonline.com/",
        Frequency: "91.9",
        location: "Takoradi",
        description: "Spice 91.9 FM is the no 1 Fante/Twi station in the region.SPICE 91.9 FM Waaye Dew!",
        icon: "https://cdn.onlineradiobox.com/img/logo/2/7022.v7.png",
        language: "Akan",
        genre: "News, Talk, Sports, Music",
        popular: true
    },
    {
        id: "197470",
        name: "Empire Fm",
        stream: "https://node-12.zeno.fm/q3391atq0twtv?rj-ttl=5&rj-tok=AAABdxzmiy0AUqHUtJ_cZwtfcQ",
        stream_1: "",
        website: "http://empirefmonline.com/",
        Frequency: "102.7",
        location: "Takoradi",
        description: "Empire 102.7 Fm is an Entertainment & Lifestyle inclined radio station located in the Oil City of Ghana (Takoradi) and owned by EIB Network.",
        icon: "https://cdn.onlineradiobox.com/img/logo/7/7017.v4.png",
        language: "Akan, English",
        genre: "News, Talk",
        popular: false
    },
    {
        id: "197471",
        name: "Connect Fm",
        stream: "https://node-04.zeno.fm/13tbqr42u8quv?rj-ttl=5&rj-tok=AAABdxzzpuYA9jSATDr69lNONQ",
        stream_1: "",
        website: "https://3news.com/",
        Frequency: "97.1",
        location: "Takoradi",
        description: "Connect FM 97.1 is a very intuitive radio station with some of the country’s leading radio programs in their day long programs schedules. They have got some programs which are popular across the country with traffic from thousands of listeners which makes Connect FM 97.1 a definitly popular radio station in the nation.",
        icon: "https://cdn.onlineradiobox.com/img/logo/3/76093.v5.png",
        language: "Akan, English",
        genre: "News, Talk, Music, variety",
        popular: false
    },
    {
        id: "197472",
        name: "West End Radio",
        stream: "https://node-27.zeno.fm/47nz3zut26duv?rj-ttl=5&rj-tok=AAABdxz5j_4AWgh97W7_GikV2Q",
        stream_1: "",
        website: "http://www.westendfmonline.com/",
        Frequency: "100.3",
        location: "Nkrofro",
        description: "Community Radio station",
        icon: "https://cdn.onlineradiobox.com/img/logo/7/85267.v7.png",
        language: "Multilingual, English",
        genre: "Entertainment, Politics, Gospel",
        popular: false
    },
    {
        id: "197473",
        name: "Kobbyros Radio",
        stream: "https://node-27.zeno.fm/47nz3zut26duv?rj-ttl=5&rj-tok=AAABdxz5j_4AWgh97W7_GikV2Q",
        stream_1: "",
        website: "http://www.kobbyrosradioonline.com/",
        Frequency: "",
        location: "Takoradi",
        description: "",
        icon: "https://cdn.onlineradiobox.com/img/logo/0/81700.v11.png",
        language: "Akan, English",
        genre: "News, Entertainment, Variety",
        popular: false
    },
    {
        id: "197474",
        name: "Melody Fm",
        stream: "http://node-20.zeno.fm/dqfht06t6mzuv?rj-ttl=5&rj-tok=AAABdx0HyjoAKioKiIRn3JBIgg",
        stream_1: "https://node-28.zeno.fm/8np9p06t6mzuv.aac?rj-ttl=5&rj-tok=AAABdx0KhewA-XsJGYMJVjjfOg",
        website: "https://melody911fm.com/",
        Frequency: "91.1",
        location: "Takoradi",
        description: "MELODY FM based in Takoradi. Western Region reflects the lives of the upscale listener, living in Ghana’s most rapidly growing region, the Western Region. Our programming is targeted at the ambitious young adult, middle aged professionals between ages 18 and 45.",
        icon: "https://cdn.onlineradiobox.com/img/logo/6/7026.v6.png",
        language: "Akan, English",
        genre: "News, Talk, Sports, Music",
        popular: false
    },
    {
        id: "197475",
        name: "Parousia Radio",
        stream: "https://node-28.zeno.fm/vg1ax9tvz1zuv.aac?rj-ttl=5&rj-tok=AAABdx0OKOIATeRO4Na-9X5L0g",
        stream_1: "",
        website: "https://zeno.fm/parousia-radio/",
        Frequency: "",
        location: "Takoradi",
        description: "Parousia Radio is purely Christian Online Radio and official radio station of Global Commission Chapel which aims at winning souls, perfecting the saints, preparing Christians for the work of the ministry, edifying the body of Christ and highlighting on the mutual Faith we have in Jesus Christ through radio broadcast. Ephesians 4:12 “For the perfecting of the saints, for the work of the ministry, for the edifying of the body of Christ. It was established on 21st April, 2017 by Rev. Joel Aidoo. Keep on enjoying our programmes and be blessed.",
        icon: "https://cdn.onlineradiobox.com/img/logo/0/92750.v2.png",
        language: "Multilingual, English",
        genre: "Gospel",
        popular: false
    },
    {
        id: "197476",
        name: "Unity Fm",
        stream: "https://node-28.zeno.fm/t4xnsadmq2zuv?rj-ttl=5&rj-tok=AAABdx0SrLIAkRyR5AhV0cW7ug",
        stream_1: "",
        website: "http://www.unityfmonline.com/",
        Frequency: "88.7",
        location: "Takoradi",
        description: "A very vibrant station inside Takoradi, Ghana.",
        icon: "https://cdn.onlineradiobox.com/img/logo/4/90474.v3.png",
        language: "Akan, English",
        genre: "News, Talk, Music, Variety",
        popular: false
    },
    {
        id: "197477",
        name: "Christ Vision Radio",
        stream: "https://node-29.zeno.fm/nszqsahumwzuv?rj-ttl=5&rj-tok=AAABdx0ZrIwAuFCnxnPxofbF-Q",
        stream_1: "",
        website: "https://christvisionradio.blogspot.com/",
        Frequency: "",
        location: "Tarkwa",
        description: "Continue the vision of Christ.",
        icon: "https://cdn.onlineradiobox.com/img/logo/9/90439.v3.png",
        language: "Akan, English",
        genre: "Gospel",
        popular: false
    },
    {
        id: "197478",
        name: "Cape Fm",
        stream: "https://freeuk5.listen2myradio.com/live.mp3?typeportmount=s1_3041_stream",
        stream_1: "",
        website: "http://www.cape933.com/",
        Frequency: "93.3",
        location: "Cape Coast",
        description: "Redefining Radio in the Central Region, Cape 93.3 the coastal vibe. Cape 93.3 It's a refreshing new attitude.",
        icon: "https://cdn.onlineradiobox.com/img/logo/8/73078.v8.png",
        language: "Akan, English",
        genre: "News, Talk, Sports, Music",
        popular: false
    },
    {
        id: "197479",
        name: "REHIC Radio",
        stream: "https://node-30.zeno.fm/hqbxxmq50tzuv.aac?rj-ttl=5&rj-tok=AAABdx0hJUsAyPXElTSQSUWYnQ",
        stream_1: "",
        website: "https://zeno.fm/rehicradio/",
        Frequency: "",
        location: "Takoradi",
        description: "Bringing Times Of Refreshing To This Generation And Beyond",
        icon: "https://cdn.onlineradiobox.com/img/logo/9/92429.v4.png",
        language: "Akan, English",
        genre: "Gospel",
        popular: false
    },
    {
        id: "197480",
        name: "Bramcom Radio Online",
        stream: "https://node-30.zeno.fm/5k38xxf1v7zuv?rj-ttl=5&rj-tok=AAABdx0o9UAAN89Op-WH21jpBw",
        stream_1: "",
        website: "https://bramcomgh.net/",
        Frequency: "",
        location: "Takoradi",
        description: "Your trusted channel.",
        icon: "https://cdn.onlineradiobox.com/img/logo/5/92385.v3.png",
        language: "Akan, English",
        genre: "Variety",
        popular: false
    },
    {
        id: "197481",
        name: "360Africa Radio",
        stream: "https://node-10.zeno.fm/5gyngmysfzzuv?rj-ttl=5&rj-tok=AAABdx05YS8AqTsc1KFbnTJr2A",
        stream_1: "",
        website: "https://360africahitz.com/",
        Frequency: "",
        location: "Takoradi",
        description: "360Africa TV & Radio is an online platform, we bring you Sports, Local News, Entertainment, World, Etc.",
        icon: "https://cdn.onlineradiobox.com/img/logo/3/88623.v1.png",
        language: "Multilingual",
        genre: "News, Talk, Sports, Music, Entertainment",
        popular: false
    },
    {
        id: "197482",
        name: "Lyke Radio",
        stream: "https://node-23.zeno.fm/hsu9hfpqutzuv?rj-ttl=5&rj-tok=AAABdx0-8AcAF5Q59ISs8nHa3w",
        stream_1: "",
        website: "https://lykeradio.com",
        Frequency: "",
        location: "Takoradi",
        description: "We are well vested in entertainment,local news,sports,etc.",
        icon: "https://cdn.onlineradiobox.com/img/logo/3/87743.v4.png",
        language: "Multilingual, English",
        genre: "News, Talk, Sports, Music, Entertainment, Gospel",
        popular: false
    },
    {
        id: "197483",
        name: "Radio NED",
        stream: "https://node-35.zeno.fm/qsa068q31tzuv?rj-ttl=5&rj-tok=AAABdx1DLUoAU00UG7izXej_Bw",
        stream_1: "",
        website: "https://donyemml.wixsite.com/nedservicesgh",
        Frequency: "",
        location: "Takoradi",
        description: "You Name, We Maintain.",
        icon: "https://cdn.onlineradiobox.com/img/logo/7/92537.v2.png",
        language: "Akan, English",
        genre: "Variety",
        popular: false
    },
    {
        id: "197484",
        name: "Oceans Snow Radio",
        stream: "https://node-11.zeno.fm/y78vzcpgvzzuv?rj-ttl=5&rj-tok=AAABdx1H8fgAlpr3cTyNIc1V1Q",
        stream_1: "",
        website: "https://zeno.fm/farm-radiouk9ptcpgvzzuv/",
        Frequency: "",
        location: "Tarkwa",
        description: "Satisfy my Soul.",
        icon: "https://cdn.onlineradiobox.com/img/logo/7/95627.v3.png",
        language: "Akan, English",
        genre: "Music, Gospel",
        popular: false
    },
    {
        id: "197485",
        name: "Oyeeman Fm",
        stream: "https://node-03.zeno.fm/yx4m460w1bruv?rj-ttl=5&rj-tok=AAABdx1OCAgABrm5iksw5bW0lQ",
        stream_1: "",
        website: "https://Oyeemanfmonline.com",
        Frequency: "106.1",
        location: "Aboso",
        description: "Oyeeman 106.1 fm is an authentic radio station in existence to broadcast to abosoman and beyond,its enclave and beyond the world.It is located at aboso in the prestea huni valley municipality.Oyeeman 106.1fm was inaugrated on the 10th of october 2020.We are here to educate,enterertain and inform the general public within the prestea huni valley municipality and beyond .We are opened for business and further discussions on 0504206106 or 0246767145.",
        icon: "https://cdn.onlineradiobox.com/img/logo/6/95076.v1.png",
        language: "Akan, English",
        genre: "News, Talk, Sports, Entertainment, Politics",
        popular: false
    },
    {
        id: "197486",
        name: "Mining City Radio",
        stream: "https://node-11.zeno.fm/33sc1skdqm0uv?rj-ttl=5&rj-tok=AAABdx1TargAAVK4WzOSSLIXCw,",
        stream_1: "https://node-05.zeno.fm/fgbfvskdqm0uv.aac?rj-ttl=5&rj-tok=AAABdx1YoX8Ahl2uaUEVpSZQRw",
        website: "https://zeno.fm/mining-city-radio-895mhz/",
        Frequency: "89.5",
        location: "Tarkwa",
        description: "Mining City Radio 89.5 Mhz",
        icon: "https://cdn.onlineradiobox.com/img/logo/5/97725.v1.png",
        language: "Akan, English",
        genre: "News, Talk, Entertainment, Politics",
        popular: false
    },
    {
        id: "197487",
        name: "Fruitful Radio",
        stream: "https://node-09.zeno.fm/zavpry0xx7zuv?rj-ttl=5&rj-tok=AAABdx1fAO8AKVWNGL-5qa1y9A",
        stream_1: "",
        website: "https://lykeradio.com",
        Frequency: "",
        location: "Tarkwa",
        description: "This is an online radio station that is dedicated to presenting to you the word of God and Good gospel music.",
        icon: "https://cdn.onlineradiobox.com/img/logo/4/92524.v1.png",
        language: "Akan, English",
        genre: "Music, Gospel",
        popular: false
    },
    {
        id: "197488",
        name: "Ghana Music Radio",
        stream: "https://streaming.radio.co/s92f890821/listen",
        stream_1: "",
        website: "http://www.ghanamusicradio.com/",
        Frequency: "",
        location: "Accra",
        description: "Ghana Music Radio is an internet radio station from Accra, Ghana providing latest, hot and classic hits from Ghana and music information.",
        icon: "https://cdn.onlineradiobox.com/img/logo/2/7042.v2.png",
        language: "Akan, English",
        genre: "Music",
        popular: false
    },
    {
        id: "197489",
        name: "Afrik Best Radio",
        stream: "https://str2b.openstream.co/571",
        stream_1: "",
        website: "https://www.afrikbestradio.online/",
        Frequency: "",
        location: "Cape Coast",
        description: "Best Music From Africa And Worldwide Under Ground Artist And Popular Artist, Shabaut Service, Promotions. Afrik Best Radio Is Producing original audio and video content, live events and exclusive programming broadcast via on-air, online and mobile platforms. Will launch your products on most of these platforms. Unlimited Listeners, Worldwide, Plays On Website, Plays In Cars, Google PLAY Android App.",
        icon: "https://cdn.onlineradiobox.com/img/logo/8/65688.v7.png",
        language: "Akan, English, Multilingual",
        genre: "Music",
        popular: false
    },
    {
        id: "197490",
        name: "Jet Radio Online",
        stream: "https://node-12.zeno.fm/9564yrw5v2quv?rj-ttl=5&rj-tok=AAABdyhKbi0A1qfGCMk-0cwJfw",
        stream_1: "",
        website: "https://zeno.fm/jet-radio-onlines2kvwrw5v2quv/",
        Frequency: "",
        location: "Kasoa",
        description: "In stead of jamming the radio with loads of programs JET RADIO ONLINE puts their emphasis to bring the best of the best programs in a relative few numbers. But, JET RADIO ONLINE tries their best to bring the quality of the programs to a next level. Listeners and their preference plays a vital role in this regard.",
        icon: "https://cdn.onlineradiobox.com/img/logo/0/78680.v9.png",
        language: "Akan, English",
        genre: "News, Talk, Sports, Music",
        popular: false
    },
    {
        id: "197491",
        name: "Kok Radio",
        stream: "https://node-09.zeno.fm/z5xgdb10tueuv?rj-ttl=5&rj-tok=AAABdyhRNhYAD5pHHiZ5Z5lGsQ",
        stream_1: "",
        website: "http://www.kokradiogh.com/",
        Frequency: "",
        location: "Cape Coast",
        description: "To promote the word of God",
        icon: "https://cdn.onlineradiobox.com/img/logo/3/75523.v2.png",
        language: "Akan, English",
        genre: "Gospel",
        popular: false
    },
    {
        id: "197492",
        name: "Obrempon Fm",
        stream: "https://node-10.zeno.fm/qr6xwu5v44zuv?rj-ttl=5&rj-tok=AAABdyhUhlwA1VQOJp-Xu7rfSg",
        stream_1: "",
        website: "http://www.obremponfmnewsroom.com/",
        Frequency: "91.7",
        location: "Swedru",
        description: "A private commercial radio station, which aims at bringing quality content to its listeners. With a fusion of both English and local languages, we provide innovative programs to our listeners with the intention to inform, educate and entertain them.",
        icon: "https://cdn.onlineradiobox.com/img/logo/6/91546.v2.png",
        language: "Akan, English",
        genre: "News, Talk, Sports, Music, Entertainment",
        popular: false
    },
    {
        id: "197493",
        name: "Obra Pa Fm",
        stream: "http://obrapafmlive.masterdigitalmedia.com:8000/live",
        stream_1: "",
        website: "http://www.otmediaonline.com/",
        Frequency: "106.9",
        location: "Kasoa",
        description: "OTMedia represents Obra Pa 106.9 Fm- Ghana and Topical Radio- Hamburg – Germay. They are two subsidiaries that exchange signals and feeds to expand the broadcast range beyond the primary coverage area for the purpose to improve services in a part of the main coverage area and to inform and transform through information to others who might receive a poor signal due to geographical constraints by the use of FM to establish a presence on the other band and to serve as a high grants of platform for advertisers to build upon their range of maximising revenue.",
        icon: "https://cdn.onlineradiobox.com/img/logo/6/75506.v10.png",
        language: "Akan, English",
        genre: "Music",
        popular: false
    },
    {
        id: "197494",
        name: "Infinity Radio GH",
        stream: "https://node-04.zeno.fm/5bpw8cyuvueuv?rj-ttl=5&rj-tok=AAABdyhgHMUAgpzXpPbAOefU_g",
        stream_1: "",
        website: "",
        Frequency: "",
        location: "Cape Coast",
        description: "Radio station to promote the word of God.",
        icon: "https://cdn.onlineradiobox.com/img/logo/6/79866.v3.png",
        language: "Akan, English",
        genre: "Gospel",
        popular: false
    }, {
        id: "197495",
        name: "Reach The World Radio",
        stream: "https://node-18.zeno.fm/u90nayh18qzuv?rj-ttl=5&rj-tok=AAABdyhi7LYAp7dB7UVHFbOhnA",
        stream_1: "",
        website: "https://zeno.fm/reachtheworldradio/",
        Frequency: "",
        location: "Cape Coast",
        description: "This is Reach the World Radio....reaching out world with the gospel of Jesus Christ.",
        icon: "https://cdn.onlineradiobox.com/img/logo/7/86127.v3.png",
        language: "Akan, English",
        genre: "Gospel",
        popular: false
    },
    {
        id: "197496",
        name: "Ahomka Fm",
        stream: "https://node-23.zeno.fm/zhgsudduzwzuv?rj-ttl=5&rj-tok=AAABdyhm9OoAYeOkX0qOMPYVJg",
        stream_1: "",
        website: "https://zeno.fm/ahomka-fm/",
        Frequency: "99.5",
        location: "Elmina",
        description: "Ahomkafm 99.5 FM is a radio station broadcast from Elmina Ghana.",
        icon: "https://cdn.onlineradiobox.com/img/logo/6/7016.v4.png",
        language: "Akan, English",
        genre: "News, Talk, Sports, Music",
        popular: false
    },
    {
        id: "197497",
        name: "Wooden Radio",
        stream: "",
        stream_1: "",
        website: "https://www.woodenradio.co/",
        Frequency: "",
        location: "Kasoa",
        description: "Wooden Radio based in Kasoa in the Central Region is one of the popular music stations. Wooden Radio station streaming music and programs both in air and online. Originally it is an African Music radio channel plays around the clock 24 hours live online. Wooden Radio also operates various musical programs consistantly for people of all ages.",
        icon: "https://cdn.onlineradiobox.com/img/logo/2/87062.v9.png",
        language: "Akan, English",
        genre: "News, Talk, Sports, Music",
        popular: false
    },
    {
        id: "197498",
        name: "Pink Fm",
        stream: "https://sp0001.opengradle.pro:8130/live.mp3",
        stream_1: "",
        website: "https://pinkfmonlinegh.com/",
        Frequency: "96.9",
        location: "Kasoa",
        description: "We are a music-oriented station with a touch of credible news content",
        icon: "https://cdn.onlineradiobox.com/img/logo/7/73537.v6.png",
        language: "Akan, English",
        genre: "Music",
        popular: false
    },
    {
        id: "197499",
        name: "Secret Fm Online",
        stream: "https://node-17.zeno.fm/rgts3k9c37zuv?rj-ttl=5&rj-tok=AAABdyhxwJwAaqeEVj3BmJOfZw",
        stream_1: "",
        website: "https://zeno.fm/secret-fm-online/",
        Frequency: "",
        location: "Swedru",
        description: "Where the secret is...",
        icon: "https://cdn.onlineradiobox.com/img/logo/7/92707.v3.png",
        language: "Akan, English",
        genre: "Variety",
        popular: false
    },
    {
        id: "197500",
        name: "Radio Visa",
        stream: "https://node-17.zeno.fm/8ds5bs4kva0uv?rj-ttl=5&rj-tok=AAABdyh0-1QAqrF7P4R2-MS05Q",
        stream_1: "",
        website: "http://www.radiovisaonline.com/",
        Frequency: "88.5",
        location: "Dunkwa",
        description: "We gives you nothing but the best",
        icon: "https://cdn.onlineradiobox.com/img/logo/1/92801.v4.png",
        language: "Akan, English",
        genre: "variety",
        popular: false
    },
    {
        id: "197501",
        name: "Obrumankuma",
        stream: "https://node-03.zeno.fm/sygvv3gtxd0uv?rj-ttl=5&rj-tok=AAABdyh31hMAxmMlv1ID0nE6qQ",
        stream_1: "",
        website: "https://zeno.fm/obrumankuma-fm/",
        Frequency: "100.7",
        location: "Cape Coast",
        description: "You can call as on 0243686085 for any of your advertisement or programme",
        icon: "https://cdn.onlineradiobox.com/img/logo/4/95404.v2.png",
        language: "Akan, English",
        genre: "Music",
        popular: false
    },
    {
        id: "197502",
        name: "Restorer Radio",
        stream: "https://node-06.zeno.fm/ygz5xb1ed2zuv?rj-ttl=5&rj-tok=AAABdyiB-8oACqDk5fgjllK25A",
        stream_1: "",
        website: "https://restorerradio.carrd.co/",
        Frequency: "",
        location: "Fenyi Yokoe",
        description: "Restorer Radio is a Online broadcast radio station in Penyi, Ghana. Providing christian music and Midnight Prayer with Pastor Alfred Acquayer",
        icon: "https://cdn.onlineradiobox.com/img/logo/1/96351.v3.png",
        language: "English, Multilingual",
        genre: "Gospel",
        popular: false
    },
    {
        id: "197503",
        name: "STANDbest FM",
        stream: "https://node-20.zeno.fm/2x9mpf7541zuv?rj-ttl=5&rj-tok=AAABdyiHUl4AizCuguVxHoJfEQ",
        stream_1: "",
        website: "",
        Frequency: "",
        location: "Ho",
        description: "Gospel radio",
        icon: "https://cdn.onlineradiobox.com/img/logo/5/89695.v2.png",
        language: "English, Multilingual",
        genre: "Gospel",
        popular: false
    },
    {
        id: "197504",
        name: "Nyatefe Radio",
        stream: "https://node-26.zeno.fm/gagafyhmh5zuv?rj-ttl=5&rj-tok=AAABdyiJ2-cAWkd2Hxi7W-MVNQ",
        stream_1: "",
        website: "",
        Frequency: "94.5",
        location: "Ho",
        description: "Welcome to the Nyatefe Radio (94.5) FM.",
        icon: "https://cdn.onlineradiobox.com/img/logo/8/93948.v3.png",
        language: "English, Multilingual",
        genre: "News, Variety",
        popular: false
    },
    {
        id: "197505",
        name: "Zaa Radio",
        stream: "http://stream.zaaradio.com:60700/Zaa",
        stream_1: "",
        website: "https://zaaradio.com/",
        Frequency: "99.3",
        location: "Tamale",
        description: "This radio station is broadcasting in Ghana. Providing latest local news, sports, politics, business, education, opinion health and so much more. It can heard at local frequency of 99.3 FM and online.",
        icon: "https://cdn.onlineradiobox.com/img/logo/8/7038.v3.png",
        language: "English, Multilingual",
        genre: "News, Talk, Sports, Music",
        popular: false
    },
    {
        id: "197506",
        name: "B-Zar Radio",
        stream: "https://node-22.zeno.fm/mbzfkyrfkzzuv?rj-ttl=5&rj-tok=AAABdyiX_LoAerhRUzCmxkUzTg",
        stream_1: "",
        website: "https://zeno.fm/b-zar-radio/",
        Frequency: "",
        location: "Wa",
        description: "B-ZAR Radio is a subsidiary of B-ZAR Multimedia Systems with the main purpose of projecting and criticising the developmental necessities of the Upper West region by way of serving voice to the voiceless in the area. We seek to also draw attention globally to our challenges being neglected by leadership and other stakeholders.",
        icon: "https://cdn.onlineradiobox.com/img/logo/2/92582.v4.png",
        language: "English, Multilingual",
        genre: "News, Talk, Sports, Music",
        popular: false
    },
    {
        id: "197507",
        name: "Tumpaani Radio Nadowli",
        stream: "https://node-08.zeno.fm/m3ccnp9mgnzuv?rj-ttl=5&rj-tok=AAABdyiaZ5sABXLkbX7vUxd2_A",
        stream_1: "",
        website: "",
        Frequency: "88.5",
        location: "Wa",
        description: "Tumpaani Radio Nadowli is a cutting edge infotainment radio station committed to enhancing the socio-cultural life of people living in the Upper West region. Is private commercial radio station in Wa and currently transmit at 1kW which covers approx. 80% of the Upper West region. TUMPAANI RADIO NADOWLI is committed to entertaining listeners through music, arts and cultural programming. We highlight the artistic talent of the community by showcasing local artists covering a spectrum of expression from traditional to experimental- reflecting the diverse cultures we serve.",
        icon: "https://cdn.onlineradiobox.com/img/logo/5/84925.v2.png",
        language: "English, Multilingual",
        genre: "News, Talk, Sports, Music",
        popular: false
    },
    {
        id: "197508",
        name: "Info Radio Ghana",
        stream: "https://node-27.zeno.fm/ey34mac27vzuv?rj-ttl=5&rj-tok=AAABdyidjk4ACEJncwCTuO-dTg",
        stream_1: "",
        website: "https://www.inforadio.online/",
        Frequency: "91.1",
        location: "Wa",
        description: "Info Radio is an innovative media company in the Upper West Region of Ghana that serves the greater good of its communities. We are a subsidiary of Kameleon Communications Ghana, a creative advertising agency in Ghana. Info Radio delivers relevant content and information to consumers across multiple platforms. Our business goal is to become the leading radio station in the Upper West Region and the rest of the country.",
        icon: "https://cdn.onlineradiobox.com/img/logo/8/86838.v3.png",
        language: "Akan, English",
        genre: "News, Talk, Sports, Music, Variety",
        popular: false
    },
    {
        id: "197509",
        name: "Echosoundz Radio",
        stream: "http://echosoundz.atunwadigital.streamguys1.com/echosoundz",
        stream_1: "",
        website: "https://echosoundzonline.com/",
        Frequency: "",
        location: "Wa",
        description: "Listen to the best music, programs and much more. From Ghana.",
        icon: "https://cdn.onlineradiobox.com/img/logo/7/76167.v3.png",
        language: "Akan, English",
        genre: "Variety",
        popular: false
    },
    {
        id: "197510",
        name: "Bryt Fm",
        stream: "https://node-28.zeno.fm/rf4rr4mkdwzuv?rj-ttl=5&rj-tok=AAABdyimcCoAI2V-gAZvTRkGVA",
        stream_1: "",
        website: "https://zeno.fm/bryt991fm/",
        Frequency: "99.1",
        location: "Koforidua",
        description: "Bryt FM is the newest FM radio station based in Koforidua in the Eastern Region. Its main objective is giving listeners the best in entertainment and Information.",
        icon: "https://cdn.onlineradiobox.com/img/logo/8/6978.v7.png",
        language: "Akan, English",
        genre: "News, Talk, Music, Enterntainment",
        popular: false
    },
    {
        id: "197511",
        name: "Dadi Fm",
        stream: "https://node-04.zeno.fm/afzd4f4nq7zuv?rj-ttl=5&rj-tok=AAABdyiroWQAN3agP4vCJME8ig",
        stream_1: "",
        website: "https://mybrytfmonline.com/live-radio/",
        Frequency: "101.1",
        location: "Nsawam",
        description: "More Than a Radio Station. Giving out the best in Music and Leading the way in Radio Broadcast.",
        icon: "https://cdn.onlineradiobox.com/img/logo/1/6981.v5.png",
        language: "Akan, English",
        genre: "News, Talk, Sports, Music",
        popular: false
    },
    {
        id: "197512",
        name: "Gibu Online Radio",
        stream: "https://node-29.zeno.fm/pm9a2u1abpeuv?rj-ttl=5&rj-tok=AAABdyiwtboAIANpHk0kdSJBxQ",
        stream_1: "",
        website: "",
        Frequency: "",
        location: "Donkorkrom",
        description: "Gibu Online Radio, education is our Passion",
        icon: "https://cdn.onlineradiobox.com/img/logo/2/93092.v2.png",
        language: "Akan, English",
        genre: "Variety",
        popular: false
    },
    {
        id: "197513",
        name: "The Oracle Radio",
        stream: "https://node-34.zeno.fm/kne6tydha8zuv?rj-ttl=5&rj-tok=AAABdyize4cAP_laoqEOBVnuHA",
        stream_1: "",
        website: "",
        Frequency: "",
        location: "Donkorkrom",
        description: "The Oracle Radio power to transform lives",
        icon: "https://cdn.onlineradiobox.com/img/logo/0/94140.v3.png",
        language: "Akan, English",
        genre: "Music",
        popular: false
    },
    {
        id: "197514",
        name: "Onioo Radio",
        stream: "https://node-33.zeno.fm/d079m8zuhnruv?rj-ttl=5&rj-tok=AAABdyi4XhAAre7yjzkNex1DrA",
        stream_1: "",
        website: "https://zeno.fm/onioo-radio/",
        Frequency: "",
        location: "Koforidua",
        description: "New TV|Radio network in Ghana west Africa",
        icon: "https://cdn.onlineradiobox.com/img/logo/0/83320.v2.png",
        language: "Akan, English",
        genre: "Variety",
        popular: false
    }, {
        id: "197515",
        name: "01 Radio",
        stream: "https://str2b.openstream.co/1812?aw_0_1st.collectionid=5250&stationId=5250&publisherId=1836&k=1611295626",
        stream_1: "",
        website: "https://flymultimediagh.com/",
        Frequency: "",
        location: "Nsawam",
        description: "01 radio is your number gosple music station that plays all your favorite gosple songs from all genres of gosple music. Just download our app and enjoy good tunez here",
        icon: "https://cdn.onlineradiobox.com/img/logo/7/93397.v2.png",
        language: "Akan, English",
        genre: "Gospel",
        popular: false
    },
    {
        id: "197516",
        name: "Jaman Fm",
        stream: "http://ca6.rcast.net:4036/stream",
        stream_1: "",
        website: "",
        Frequency: "103.7",
        location: "Drobo",
        description: "Jaman 103.7 MHz core responsibility is to serve the people of Jaman better through Entertainment, Politics, Education, Health and developmental issues. Jaman 103.7MHz is the Newest Sensation in communication in Jaman South Municipality, Jaman Radio is second to none. Jaman Radio--- Asomdwe Nkoaaa.",
        icon: "https://cdn.onlineradiobox.com/img/logo/2/80002.v3.png",
        language: "Akan, English",
        genre: "News, Talk, Sports, Music, Entertainment",
        popular: false
    },
    {
        id: "197517",
        name: "Akomapa FM",
        stream: "http://mounthoreb1.primcast.com:8210/;",
        stream_1: "",
        website: "http://akomapafmoline.com/",
        Frequency: "89.3",
        location: "Berekum",
        description: "Akomapa FM is a christian Service radio station founded by Evangelist Bright with the aim of spreading the good news of Jesus Christ.",
        icon: "https://cdn.onlineradiobox.com/img/logo/4/7084.v3.png",
        language: "Akan, English",
        genre: "Gospel",
        popular: false
    },
    {
        id: "197518",
        name: "Ewiase FM",
        stream: "http://198.50.156.92:9029/stream",
        stream_1: "",
        website: "http://ewiasefm.com/",
        Frequency: "95.7",
        location: "Wenchi",
        description: "Ewiase 95.7 FM is the modern radio station with a state of the art working and human staff dedicated to proving great music, sports, politics, entertainment, and reality shows for the betterment of the people. Ewiase 95.7 FM seeks to report, produce, acquire and distribute news, information and other relevant content that upholds the highest standards of public service in journalism and cultural expression.",
        icon: "https://cdn.onlineradiobox.com/img/logo/1/84821.v7.png",
        language: "Akan, English",
        genre: "News, Talk, Sports, Music, Entertainment",
        popular: false
    },
    {
        id: "197519",
        name: "Anidaso Fm",
        stream: "https://stream.lensnetworks.com/proxy/anidasofm?mp=/stream",
        stream_1: "",
        website: "https://anidasofmonline.com/",
        Frequency: "101.5",
        location: "Japekrom",
        description: "Anidaso 101.5fm is Ghana's new 'Sunshine Station', situated in Japekrom, in the Brong Ahafo Region of Ghana. One of Ghana's newly established stations, Anidaso Fm brings fun shows, up tempo music, competitions, life sports broadcasts, and hi youth energy.",
        icon: "https://cdn.onlineradiobox.com/img/logo/0/7030.v10.png",
        language: "Akan, English",
        genre: "News, Talk, Sports, Music, variety",
        popular: false
    },
    {
        id: "197520",
        name: "Moonlite Fm",
        stream: "https://stream.lensnetworks.com/proxy/moonlite?mp=/stream",
        stream_1: "",
        website: "https://www.moonlitefm.com/",
        Frequency: "102.3",
        location: " Sunyani",
        description: "Moonlite102.3 FM, the best there was, the best there is and the best there shall ever be !!!!",
        icon: "https://cdn.onlineradiobox.com/img/logo/7/88347.v5.png",
        language: "Akan, English",
        genre: "Music",
        popular: false
    },
    {
        id: "197521",
        name: "WizRadio GH",
        stream: "https://node-26.zeno.fm/03uwxyf31mzuv?rj-ttl=5&rj-tok=AAABdyjYDTsABxFvyw6WglZPDw",
        stream_1: "",
        website: "https://www.wizradiogh.socialmediagh.com/",
        Frequency: "",
        location: "Techiman",
        description: "The best online radio station serving Ghana and the diaspora",
        icon: "https://cdn.onlineradiobox.com/img/logo/8/84468.v3.png",
        language: "Akan, English",
        genre: "News, Talk, Music",
        popular: false
    },
    // {
    //     id: "197520",
    //     name: "",
    //     stream: "",
    //     stream_1: "",
    //     website: "",
    //     Frequency: "",
    //     location: "Takoradi",
    //     description: "",
    //     icon: "",
    //     language: "Akan, English",
    //     genre: "News, Talk, Sports, Music",
    //     popular: false
    // },
    // {
    //     id: "197520",
    //     name: "",
    //     stream: "",
    //     stream_1: "",
    //     website: "",
    //     Frequency: "",
    //     location: "Takoradi",
    //     description: "",
    //     icon: "",
    //     language: "Akan, English",
    //     genre: "News, Talk, Sports, Music",
    //     popular: false
    // },
]
export default radiostations;